SistemaConsultaMedica/Models/Entities/Consulta.cs
using SistemaConsultaMedica.Models.Enums;

namespace SistemaConsultaMedica.Models.Entities;

public class Consulta
{
    public int Id { get; set; }
    public DateTime Data { get; set; }
    public TipoConsulta Tipo { get; set; }
    public int IdPaciente { get; set; }
    public int IdMedico { get; set; }
    public Paciente Paciente { get; set; } = null!;
    public Medico Medico { get; set; } = null!;
}

SistemaConsultaMedica/ViewModels/Consultas/AdicionarConsultaViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SistemaConsultaMedica.Models.Enums;

namespace SistemaConsultaMedica.ViewModels.Consultas;

public class AdicionarConsultaViewModel
{
    [DataType(DataType.Date)]
    public DateTime Data { get; set; }
    
    public TipoConsulta Tipo { get; set; }
    
    [Display(Name = "Paciente")]
    public int IdPaciente { get; set; }
    
    [Display(Name = "Médico")]
    public int IdMedico { get; set; }
}

SistemaConsultaMedica/ViewModels/Consultas/EditarConsultaViewModel.cs
using System.ComponentModel.DataAnnotations;
using SistemaConsultaMedica.Models.Enums;

namespace SistemaConsultaMedica.ViewModels.Consultas;

public class EditarConsultaViewModel
{
    [DataType(DataType.Date)]
    public DateTime Data { get; set; }
    
    public TipoConsulta Tipo { get; set; }
    
    [Display(Name = "Paciente")]
    public int IdPaciente { get; set; }

    public string NamePaciente { get; set; } = string.Empty;
    
    [Display(Name = "Médico")]
    public int IdMedico { get; set; }
}

SistemaConsultaMedica/ViewModels/Consultas/ListarConsultaViewModel.cs
namespace SistemaConsultaMedica.ViewModels.Consultas;

public class ListarConsultaViewModel
{
    public int Id { get; set; }
    
    public string Paciente { get; set; } = string.Empty;
    
    public string Medico { get; set; } = string.Empty;
    
    public string Tipo { get; set; } = string.Empty;
    
    public DateTime Data { get; set; }
}

SistemaConsultaMedica/Controllers/ConsultasController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaConsultaMedica.Models.Contexts;
using SistemaConsultaMedica.Models.Entities;
using SistemaConsultaMedica.Models.Enums;
using SistemaConsultaMedica.ViewModels.Consultas;

namespace SistemaConsultaMedica.Controllers;

public class ConsultasController : Controller
{
    private readonly SisMedContext _context;
    private readonly IValidator<AdicionarConsultaViewModel> _adicionarConsultaValidator;
    private readonly IValidator<EditarConsultaViewModel> _editarConsultaValidator;
    
    private const int tamanhoPagina = 10;

    public ConsultasController(SisMedContext context, IValidator<AdicionarConsultaViewModel> adicionarConsultaValidator, IValidator<EditarConsultaViewModel> editarConsultaValidator)
    {
        _context = context;
        _adicionarConsultaValidator = adicionarConsultaValidator;
        _editarConsultaValidator = editarConsultaValidator;
    }

    public IActionResult Index(string filtro, int pagina = 1)
    {
        var query = _context.Consultas
            .Include(c => c.Paciente)
            .Include(c => c.Medico)
            .AsQueryable();

        if (!string.IsNullOrWhiteSpace(filtro))
        {
            query = query.Where(c => c.Paciente.Name.Contains(filtro) || c.Medico.Name.Contains(filtro));
        }

        var consultas = query
            .OrderBy(c => c.Data)
            .Select(c => new ListarConsultaViewModel
            {
                Id = c.Id,
                Paciente = c.Paciente.Name,
                Medico = c.Medico.Name,
                Data = c.Data,
                Tipo = c.Tipo == TipoConsulta.Eletiva ? "Eletiva" : "Urgencia"
            });

        ViewBag.Filtro = filtro;
        ViewBag.NumeroPagina = pagina;
        ViewBag.TotalPaginas = Math.Ceiling((decimal)consultas.Count() / tamanhoPagina);

        var consultasPaginadas = consultas
            .Skip((pagina - 1) * tamanhoPagina)
            .Take(tamanhoPagina)
            .ToList();

        return View(consultasPaginadas);
    }

    public IActionResult Adicionar()
    {

        ViewBag.TiposConsulta = new[]
        {
            new SelectListItem { Text = "Eletiva", Value = TipoConsulta.Eletiva.ToString() },
            new SelectListItem { Text = "Urgência", Value = TipoConsulta.Urgencia.ToString() },
        };
        
        ViewBag.Medicos = _context.Medicos.OrderBy(x => x.Name).Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Adicionar(AdicionarConsultaViewModel dados)
    {

        var validacao = _adicionarConsultaValidator.Validate(dados);

        if (!validacao.IsValid)
        {
            ViewBag.TiposConsulta = new[]
            {
                new SelectListItem { Text = "Eletiva", Value = TipoConsulta.Eletiva.ToString() },
                new SelectListItem { Text = "Urgência", Value = TipoConsulta.Urgencia.ToString() },
            };
        
            ViewBag.Medicos = _context.Medicos.OrderBy(x => x.Name).Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
            
            validacao.AddToModelState(ModelState, string.Empty);
            return View(dados);
        }

        var consulta = new Consulta
        {
            Data = dados.Data,
            IdPaciente = dados.IdPaciente,
            IdMedico = dados.IdMedico,
            Tipo = dados.Tipo
        };

        _context.Consultas.Add(consulta);
        _context.SaveChanges();

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Editar(int id)
    {
        var consulta = _context.Consultas.Include(x => x.Paciente)
            .FirstOrDefault(x => x.Id == id);

        if (consulta != null)
        {
            ViewBag.TiposConsulta = new[]
            {
                new SelectListItem { Text = "Eletiva", Value = TipoConsulta.Eletiva.ToString() },
                new SelectListItem { Text = "Urgência", Value = TipoConsulta.Urgencia.ToString() },
            };
        
            ViewBag.Medicos = _context.Medicos.OrderBy(x => x.Name).Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
            
            return View(new EditarConsultaViewModel
            {
                IdMedico = consulta.IdMedico,
                IdPaciente = consulta.IdPaciente,
                NamePaciente = consulta.Paciente.Name,
                Data = consulta.Data,
                Tipo = consulta.Tipo
            });
        }

        return NotFound();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]

    public IActionResult Editar(int id, EditarConsultaViewModel dados)
    {
        var validacao = _editarConsultaValidator.Validate(dados);

        if (!validacao.IsValid)
        {
            ViewBag.TiposConsulta = new[]
            {
                new SelectListItem { Text = "Eletiva", Value = TipoConsulta.Eletiva.ToString() },
                new SelectListItem { Text = "Urgência", Value = TipoConsulta.Urgencia.ToString() },
            };
        
            ViewBag.Medicos = _context.Medicos.OrderBy(x => x.Name).Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
            
            validacao.AddToModelState(ModelState, string.Empty);
            return View(dados);
        }
        
        var consulta = _context.Consultas.Find(id);

        if (consulta != null)
        {
            consulta.Data = dados.Data;
            consulta.IdPaciente = dados.IdPaciente;
            consulta.IdMedico = dados.IdMedico;
            consulta.Tipo = dados.Tipo;

            _context.Consultas.Update(consulta);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        
        return NotFound();
    }
}

SistemaConsultaMedica/Views/Consultas/Adicionar.cshtml
@model SistemaConsultaMedica.ViewModels.Consultas.AdicionarConsultaViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Registrar consulta</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Adicionar">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="control-label" asp-for="Data"></label>
                            <input asp-for="Data" class="form-control">
                            <span asp-validation-for="Data" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="Tipo"></label>
                            <select asp-for="Tipo" class="form-control" asp-items="@ViewBag.TiposConsulta"></select>
                            <span asp-validation-for="Tipo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="IdMedico"></label>
                            <select asp-for="IdMedico" class="form-control" asp-items="@ViewBag.Medicos"></select>
                            <span asp-validation-for="IdMedico" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IdPaciente" class="control-label"></label>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Buscar paciente" id="NomePaciente"
                                       readonly>
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-default" id="BtnBuscarPaciente"
                                            data-toggle="modal" data-target="#ModalPacientes">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                            <input type="hidden" asp-for="IdPaciente" class="form-control" id="IdPaciente">
                            <span asp-validation-for="IdPaciente" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-sm btn-primary" type="submit">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<div class="modal" id="ModalPacientes">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    Buscar paciente
                </h5>
                <button class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Buscar paciente" id="TxtFiltro">
                            <div class="input-group-append">
                                <button class="btn btn-default" id="BtnBuscar">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-hover table-sm d-none" id="TbPacientes">
                    <thead>
                    <th style="width:150px">CPF</th>
                    <th>Nome</th>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
                <div class="alert alert-warning d-none" id="DivMensagem">Nenhum paciente localizado.</div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        function buscarPacientes() {
            if ($("#TxtFiltro").val().trim().length > 0) {
                $.getJSON("/Pacientes/Buscar", {filtro: $("#TxtFiltro").val()}, function (resultado) {
                    if (resultado.length > 0) {
                        var linhas = resultado.map(x => "<tr data-dismiss='modal' style='cursor:pointer;' title='Clique para selecioar' data-id='" + x.id + "'><td mask='999.999" +
                            "999-99'>" + x.cpf + "</td><td>" + x.name + "</td></tr>").join("");
                        $("#TbPacientes tbody").html(linhas);
                        $("td[mask]").each(function (e) {
                            $(this).mask($(this).attr('mask'));
                        });
                        $("#TbPacientes tbody tr").click(function () {
                            var id = $(this).attr("data-id");
                            var name = $(this).children()[1].innerText;
                            $("#IdPaciente").val(id);
                            $("#NomePaciente").val(name);
                        });
                        $("#TbPacientes").removeClass("d-none");
                        $("#DivMensagem").addClass("d-none");
                    } else {
                        $("#TbPacientes").addClass("d-none");
                        $("#DivMensagem").removeClass("d-none");
                    }
                });
            }
        }
        $("#TxtFiltro").keypress(function (e) {
            if (e.keyCode == 13) {
                buscarPacientes();
            }
        });
        
        $("#BtnBuscar").click(function () {
            buscarPacientes();
        });
    </script>
}

SistemaConsultaMedica/Views/Consultas/Editar.cshtml
@model SistemaConsultaMedica.ViewModels.Consultas.EditarConsultaViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Editar consulta</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Editar">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="control-label" asp-for="Data"></label>
                            <input asp-for="Data" class="form-control">
                            <span asp-validation-for="Data" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="Tipo"></label>
                            <select asp-for="Tipo" class="form-control" asp-items="@ViewBag.TiposConsulta"></select>
                            <span asp-validation-for="Tipo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="IdMedico"></label>
                            <select asp-for="IdMedico" class="form-control" asp-items="@ViewBag.Medicos"></select>
                            <span asp-validation-for="IdMedico" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IdPaciente" class="control-label"></label>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Buscar paciente" asp-for="NamePaciente" id="NomePaciente"
                                       readonly>
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-default" id="BtnBuscarPaciente"
                                            data-toggle="modal" data-target="#ModalPacientes">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                            <input type="hidden" asp-for="IdPaciente" class="form-control" id="IdPaciente">
                            <span asp-validation-for="IdPaciente" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-sm btn-primary" type="submit">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<div class="modal" id="ModalPacientes">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    Buscar paciente
                </h5>
                <button class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Buscar paciente" id="TxtFiltro">
                            <div class="input-group-append">
                                <button class="btn btn-default" id="BtnBuscar">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-hover table-sm d-none" id="TbPacientes">
                    <thead>
                    <th style="width:150px">CPF</th>
                    <th>Nome</th>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
                <div class="alert alert-warning d-none" id="DivMensagem">Nenhum paciente localizado.</div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        function buscarPacientes() {
            if ($("#TxtFiltro").val().trim().length > 0) {
                $.getJSON("/Pacientes/Buscar", {filtro: $("#TxtFiltro").val()}, function (resultado) {
                    if (resultado.length > 0) {
                        var linhas = resultado.map(x => "<tr data-dismiss='modal' style='cursor:pointer;' title='Clique para selecioar' data-id='" + x.id + "'><td mask='999.999" +
                            "999-99'>" + x.cpf + "</td><td>" + x.name + "</td></tr>").join("");
                        $("#TbPacientes tbody").html(linhas);
                        $("td[mask]").each(function (e) {
                            $(this).mask($(this).attr('mask'));
                        });
                        $("#TbPacientes tbody tr").click(function () {
                            var id = $(this).attr("data-id");
                            var name = $(this).children()[1].innerText;
                            $("#IdPaciente").val(id);
                            $("#NomePaciente").val(name);
                        });
                        $("#TbPacientes").removeClass("d-none");
                        $("#DivMensagem").addClass("d-none");
                    } else {
                        $("#TbPacientes").addClass("d-none");
                        $("#DivMensagem").removeClass("d-none");
                    }
                });
            }
        }
        $("#TxtFiltro").keypress(function (e) {
            if (e.keyCode == 13) {
                buscarPacientes();
            }
        });
        
        $("#BtnBuscar").click(function () {
            buscarPacientes();
        });
    </script>
}

SistemaConsultaMedica/Views/Consultas/Index.cshtml
@model IEnumerable<SistemaConsultaMedica.ViewModels.Consultas.ListarConsultaViewModel>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Consultas</h1>
            </div>
        </div>
    </div>
</section>

<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <form asp-action="Index">
                            <div class="input-group input-group-sm" style="width: 300px;">
                                <input type="text" class="form-control" placeholder="Buscar consulta" name="filtro"
                                       value="@ViewBag.Filtro">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <a href="/consultas/adicionar" class="btn btn-outline-primary btn-sm">Nova consulta</a>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-head-fixed text-nowrap table-hover">
                        <thead>
                        <tr>
                            <th style="width: 100px">Data</th>
                            <th>Paciente</th>
                            <th>Medico</th>
                            <th style="width: 40px"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var c in Model)
                        {
                            <tr>
                                <td>@c.Data.ToString("dd/MM/yyyy")</td>
                                <td>@c.Paciente</td>
                                <td>@c.Medico</td>
                                <td>
                                    <a href="/consultas/editar/@c.Id" class="btn btn-sm btn-secondary mr-1"
                                       title="Editar consulta">
                                        <span class="fas fa-edit"></span>
                                    </a>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    @if (ViewBag.TotalPaginas > 0)
                    {
                        <ul class="pagination pagination-sm m-0 float-right">
                            @if (ViewBag.NumeroPagina > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link"
                                       href="@Url.Action("Index", "Consultas", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina - 1 })">
                                        &laquo;
                                    </a>
                                </li>
                            }
                            <li class="page-item page-link">Página @ViewBag.NumeroPagina de @ViewBag.TotalPaginas</li>
                            @if (ViewBag.NumeroPagina < @ViewBag.TotalPaginas)
                            {
                                <li class="page-item">
                                    <a class="page-link"
                                       href="@Url.Action("Index", "Consultas", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina + 1 })">
                                        &raquo;
                                    </a>
                                </li>
                            }
                        </ul>
                    }
                </div>
            </div>
        </div>
    </div>
</div>