SistemaConsultaMedica/Models/Entities/Paciente.cs
namespace SistemaConsultaMedica.Models.Entities;

public class Paciente
{
    public int Id { get; set; }

    public string CPF { get; set; } = string.Empty;
    
    public string Name { get; set; } = string.Empty;
    
    public DateTime DataNascimento { get; set; }

    public InformacoesComplementaresPaciente? InformacoesComplementares { get; set; }

    public ICollection<MonitoriamentoPaciente> Monitoramentos { get; set; } = null!;
    
    public ICollection<Consulta> Consultas { get; set; } = null!;
}

SistemaConsultaMedica/Models/Entities/Pacientes.cs
namespace SistemaConsultaMedica.Models.Entities;

public class Pacientes
{
    public int Id { get; set; }

    public string CPF { get; set; } = string.Empty;
    
    public string Name { get; set; } = string.Empty;
    
    public DateTime DataNascimento { get; set; }
}

SistemaConsultaMedica/ViewModels/Pacientes/AdicionarPacienteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaConsultaMedica.ViewModels.Pacientes;

public class AdicionarPacienteViewModel
{
    public string CPF { get; set; } = string.Empty;
    
    [Display(Name="Nome")]
    [DataType(DataType.Text)]
    public string Name { get; set; } = string.Empty;
    
    [Display(Name="Data de Nascimento")]
    [DataType(DataType.Date)]
    public DateTime DataNascimento { get; set; }
}

SistemaConsultaMedica/ViewModels/Pacientes/EditarPacienteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaConsultaMedica.ViewModels.Pacientes;

public class EditarPacienteViewModel
{
    public int Id { get; set; }
    public string CPF { get; set; } = string.Empty;
    
    [Display(Name = "Nome")]
    [DataType(DataType.Text)]
    public string Name { get; set; } = string.Empty;
    
    [Display(Name = "Data de Nascimento")]
    [DataType(DataType.Date)]
    public DateTime DataNascimento { get; set; }
    
    public string? Alergias { get; set; }
    
    [Display(Name = "Medicamentos em Uso")]
    public string? MedicamentosEmUso { get; set; }
    
    [Display(Name = "Cirurgias Realizadas")]
    public string? CirurgiasRealizadas { get; set; }
}

SistemaConsultaMedica/ViewModels/Pacientes/ListarPacienteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaConsultaMedica.ViewModels.Pacientes;

public class ListarPacienteViewModel
{
    public int Id { get; set; }
    
    public string CPF { get; set; } = string.Empty;
    
    [Display(Name = "Nome")]
    [DataType(DataType.Text)]
    public string Name { get; set; } = string.Empty;
    
    [Display(Name = "Data de Nascimento")]
    [DataType(DataType.Date)]
    public DateTime DataNascimento { get; set; }
    
}

SistemaConsultaMedica/ViewModels/Pacientes/ListarPacientesViewModel.cs
namespace SistemaConsultaMedica.ViewModels.Pacientes;

public class ListarPacientesViewModel
{
    public int Id { get; set; }
    
    public string CPF { get; set; } = string.Empty;
    
    public string Name { get; set; } = string.Empty;
    
    public DateTime DataNascimento { get; set; }
    
}

SistemaConsultaMedica/Controllers/PacientesController.cs
using System.Text.RegularExpressions;
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using SistemaConsultaMedica.Models.Contexts;
using SistemaConsultaMedica.Models.Entities;
using SistemaConsultaMedica.ViewModels.Pacientes;


namespace SistemaConsultaMedica.Controllers;

public class PacientesController : Controller
{
    private readonly SisMedContext _context;
    private readonly IValidator<AdicionarPacienteViewModel> _adicionarPacienteValidator;
    private readonly IValidator<EditarPacienteViewModel> _editarPacienteValidator;
    private const int tamanhoPagina = 10;

    public PacientesController(SisMedContext context, IValidator<AdicionarPacienteViewModel> adicionarPacienteValidator,
        IValidator<EditarPacienteViewModel> editarPacienteValidator)
    {
        _context = context;
        _adicionarPacienteValidator = adicionarPacienteValidator;
        _editarPacienteValidator = editarPacienteValidator;
    }

    public IActionResult Index(string filtro, int pagina = 1)
    {
        var query = _context.Pacientes.AsQueryable();
        
        if(!string.IsNullOrWhiteSpace(filtro))
        {
            query = query.OrderBy(x => x.Name).Where(x => x.Name.Contains(filtro) || x.CPF.Contains(filtro));
        }
        
        var pacientes = query
            .Select(x => new ListarPacienteViewModel
            {
                Id = x.Id,
                CPF = x.CPF,
                Name = x.Name
            });

        ViewBag.Filtro = filtro;
        ViewBag.NumeroPagina = pagina;
        ViewBag.TotalPaginas = Math.Ceiling((decimal)pacientes.Count() / tamanhoPagina);
        
        var pacientesPaginados = pacientes
            .Skip((pagina - 1) * tamanhoPagina)
            .Take(tamanhoPagina)
            .ToList();
        
        return View(pacientesPaginados);
        
    }

    public IActionResult Adicionar()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Adicionar(AdicionarPacienteViewModel dados)
    {
        var validacao = _adicionarPacienteValidator.Validate(dados);

        if (!validacao.IsValid)
        {
            validacao.AddToModelState(ModelState, string.Empty);
            return View(dados);
        }

        var paciente = new Paciente
        {
            CPF = Regex.Replace(dados.CPF, "[^0-9]", ""),
            Name = dados.Name,
            DataNascimento = dados.DataNascimento
        };

        _context.Pacientes.Add(paciente);
        _context.SaveChanges();

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Editar(int id)
    {
        var paciente = _context.Pacientes.Find(id);

        if (paciente != null)
        {
            var informacoesComplementares = _context.InformacoesComplementaresPaciente.FirstOrDefault(x => x.IdPaciente == id);

            return View(new EditarPacienteViewModel
            {
                Id = paciente.Id,
                CPF = paciente.CPF,
                Name = paciente.Name,
                DataNascimento = paciente.DataNascimento,
                Alergias = informacoesComplementares?.Alergias,
                MedicamentosEmUso = informacoesComplementares?.MedicamentosEmUso,
                CirurgiasRealizadas = informacoesComplementares?.CirurgiasRealizadas
            });
        }

        return NotFound();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Editar(int id, EditarPacienteViewModel dados)
    {
        var validacao = _editarPacienteValidator.Validate(dados);

        if (!validacao.IsValid)
        {
            validacao.AddToModelState(ModelState, string.Empty);
            return View(dados);
        }

        var paciente = _context.Pacientes.Find(id);

        if (paciente != null)
        {
            paciente.CPF = Regex.Replace(dados.CPF, "[^0-9]", "");
            paciente.Name = dados.Name;
            paciente.DataNascimento = dados.DataNascimento;

            var informacoesComplementares = _context.InformacoesComplementaresPaciente.FirstOrDefault(x => x.IdPaciente == id);

            if (informacoesComplementares == null)
            {
                informacoesComplementares = new InformacoesComplementaresPaciente();
            }

            informacoesComplementares.Alergias = dados.Alergias;
            informacoesComplementares.MedicamentosEmUso = dados.MedicamentosEmUso;
            informacoesComplementares.CirurgiasRealizadas = dados.CirurgiasRealizadas;
            informacoesComplementares.IdPaciente = id;

            if (informacoesComplementares.Id > 0)
            {
                _context.InformacoesComplementaresPaciente.Update(informacoesComplementares);
            }
            else
            {
                _context.InformacoesComplementaresPaciente.Add(informacoesComplementares);
            }

            _context.Pacientes.Update(paciente);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        return NotFound();
    }

    public IActionResult Excluir(int id)
    {
        var paciente = _context.Pacientes.Find(id);

        if (paciente != null)
        {
            return View(new ListarPacienteViewModel
            {
                Id = paciente.Id,
                CPF = paciente.CPF,
                Name = paciente.Name
            });
        }

        return NotFound();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Excluir(int id, EditarPacienteViewModel dados)
    {
        var paciente = _context.Pacientes.Find(id);

        if (paciente != null)
        {
            _context.Pacientes.Remove(paciente);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        return NotFound();
    }

    public IActionResult Buscar(string filtro)
    {
        var pacientes = _context.Pacientes
            .Where(x => x.Name.Contains(filtro) || x.CPF.Contains(filtro))
            .Take(10)
            .Select(x => new ListarPacienteViewModel
            {
                Id = x.Id,
                CPF = x.CPF,
                Name = x.Name
            });

        return Json(pacientes);
    }
}

SistemaConsultaMedica/Views/Pacientes/Adicionar.cshtml
@model SistemaConsultaMedica.ViewModels.Pacientes.AdicionarPacienteViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cadastrar Pacientes</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Adicionar">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="control-label" asp-for="CPF"></label>
                            <input asp-for="CPF" class="form-control" mask="000.000.000-00">
                            <span asp-validation-for="CPF" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="Name"></label>
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="DataNascimento"></label>
                            <input asp-for="DataNascimento" class="form-control">
                            <span asp-validation-for="DataNascimento" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-sm btn-primary" type="submit">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

SistemaConsultaMedica/Views/Pacientes/Editar.cshtml
@model SistemaConsultaMedica.ViewModels.Pacientes.EditarPacienteViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Editar Pacientes</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Editar">
                <div class="card">
                    <div class="card-body">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="form-group">
                            <label class="control-label" asp-for="CPF"></label>
                            <input asp-for="CPF" class="form-control" mask="000.000.000-00">
                            <span asp-validation-for="CPF" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="Name"></label>
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="DataNascimento"></label>
                            <input asp-for="DataNascimento" class="form-control">
                            <span asp-validation-for="DataNascimento" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="Alergias"></label>
                            <input asp-for="Alergias" class="form-control">
                            <span asp-validation-for="Alergias" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="MedicamentosEmUso"></label>
                            <input asp-for="MedicamentosEmUso" class="form-control">
                            <span asp-validation-for="MedicamentosEmUso" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="CirurgiasRealizadas"></label>
                            <input asp-for="CirurgiasRealizadas" class="form-control">
                            <span asp-validation-for="CirurgiasRealizadas" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col">
                                <a href="/pacientes/excluir/@Model.Id" class="btn btn-danger btn-sm">Excluir</a>
                            </div>
                            <div class="col text-right">
                                <button class="btn btn-sm btn-primary" type="submit">Salvar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

SistemaConsultaMedica/Views/Pacientes/Excluir.cshtml
@model SistemaConsultaMedica.ViewModels.Pacientes.ListarPacienteViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Excluir Pacientes</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="alert alert-danger">
        <span class="fas fa-warning"></span>
        Deseja realmente excluir este cadastro?
    </div>
    <div class="row">
        <div class="col-12">
            <form asp-action="Excluir">
                <div class="card card-outline card-danger">
                    <div class="card-body">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="form-group">
                            <label class="control-label" asp-for="CPF"></label>
                            <input asp-for="CPF" class="form-control" mask="000.000.000-00" readonly>
                            <span asp-validation-for="CPF" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="Name"></label>
                            <input asp-for="Name" class="form-control" readonly>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="DataNascimento"></label>
                            <input asp-for="DataNascimento" class="form-control" readonly>
                            <span asp-validation-for="DataNascimento" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col text-right">
                                <button class="btn btn-sm btn-danger" type="submit">Excluir</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

SistemaConsultaMedica/Views/Pacientes/Index.cshtml
@model IEnumerable<SistemaConsultaMedica.ViewModels.Pacientes.ListarPacienteViewModel>


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Pacientes</h1>
            </div>
        </div>
    </div>
</section>

<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <form asp-action="Index">
                            <div class="input-group input-group-sm" style="width: 300px;">
                                <input type="text" class="form-control" placeholder="Buscar paciente" name="filtro"
                                       value="@ViewBag.Filtro">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <a href="/pacientes/Adicionar" class="btn btn-outline-primary btn-sm">Novo paciente</a>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-head-fixed text-nowrap table-hover">
                        <thead>
                        <tr>
                            <th style="width: 200px">CPF</th>
                            <th>Nome</th>
                            <th style="width: 40px"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var paciente in Model)
                        {
                            <tr>
                                <td mask="000.000.000-00">@paciente.CPF
                                </td>
                                <td>
                                    @paciente.Name
                                </td>
                                <td>
                                    <a href="/pacientes/editar/@paciente.Id" class="btn btn-sm btn-secondary mr-1"
                                       title="Editar médico">
                                        <span class="fas fa-edit"></span>
                                    </a>
                                    <a href="/monitoramento?idPaciente=@paciente.Id" class="btn btn-sm btn-secondary mr-1"
                                       title="Monitoramento de sinais vitais">
                                        <span class="fas fa-list"></span>
                                    </a>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    @if (ViewBag.TotalPaginas > 0)
                    {
                        <ul class="pagination pagination-sm m-0 float-right">
                            @if (ViewBag.NumeroPagina > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link"
                                       href="@Url.Action("Index", "Pacientes", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina - 1 })">
                                        &laquo;
                                    </a>
                                </li>
                            }
                            <li class="page-item page-link">Página @ViewBag.NumeroPagina de @ViewBag.TotalPaginas</li>
                            @if (ViewBag.NumeroPagina < @ViewBag.TotalPaginas)
                            {
                                <li class="page-item">
                                    <a class="page-link"
                                       href="@Url.Action("Index", "Pacientes", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina + 1 })">
                                        &raquo;
                                    </a>
                                </li>
                            }
                        </ul>
                    }
                </div>
            </div>
        </div>
    </div>
</div>