SistemaConsultaMedica/Models/Entities/Medico.cs
namespace SistemaConsultaMedica.Models.Entities
{
    public class Medico
    {
        public int Id { get; set; }

        public string CRM { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;

        public ICollection<Consulta> Consultas { get; set; } = null!;
    }
}

SistemaConsultaMedica/ViewModels/Medicos/AdicionarMedicoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaConsultaMedica.ViewModels.Medicos;

public class AdicionarMedicoViewModel
{
    public string CRM { get; set; } = string.Empty;
    
    [Display(Name = "Nome")]
    [DataType(DataType.Text)]
    public string Name { get; set; } = string.Empty;
}

SistemaConsultaMedica/ViewModels/Medicos/EditarMedicoViewModel.cs
namespace SistemaConsultaMedica.ViewModels.Medicos;

public class EditarMedicoViewModel
{
    public int Id { get; set; }
    public string CRM { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
}

SistemaConsultaMedica/ViewModels/Medicos/ListarMedicoViewModel.cs
namespace SistemaConsultaMedica.ViewModels.Medicos;

public class ListarMedicoViewModel
{
    public int Id { get; set; }

    public string CRM { get; set; } = string.Empty;

    public string Name { get; set; } = string.Empty;
}

SistemaConsultaMedica/Controllers/MedicosController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using SistemaConsultaMedica.Models.Contexts;
using SistemaConsultaMedica.Models.Entities;
using SistemaConsultaMedica.ViewModels.Medicos;

namespace SistemaConsultaMedica.Controllers;

public class MedicosController : Controller
{
    // GET
    private readonly SisMedContext _context;
    private readonly IValidator<AdicionarMedicoViewModel> _adicionarMedicoValidator;
    private readonly IValidator<EditarMedicoViewModel> _editarMedicoValidator;
    private const int tamanhoPagina = 10;

    public MedicosController(SisMedContext context, IValidator<AdicionarMedicoViewModel> adicionarMedicoValidator, IValidator<EditarMedicoViewModel> editarMedicoValidator)
    {
        _context = context;
        _adicionarMedicoValidator = adicionarMedicoValidator;
        _editarMedicoValidator = editarMedicoValidator;
    }

    public IActionResult Index(string filtro, int pagina = 1)
    {
        var query = _context.Medicos.AsQueryable();

        if (!string.IsNullOrWhiteSpace(filtro))
        {
            query = query.OrderBy(x => x.Name).Where(x => x.Name.Contains(filtro) || x.CRM.Contains(filtro));
        }

        var medicos = query
            .Select(x => new ListarMedicoViewModel
            {
                Id = x.Id,
                CRM = x.CRM,
                Name = x.Name
            });

        ViewBag.Filtro = filtro;
        ViewBag.NumeroPagina = pagina;
        ViewBag.TotalPaginas = Math.Ceiling((decimal)medicos.Count() / tamanhoPagina);

        var medicosPaginados = medicos
            .Skip((pagina - 1) * tamanhoPagina)
            .Take(tamanhoPagina)
            .ToList();

        return View(medicosPaginados);
    }


    public IActionResult Adicionar()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Adicionar(AdicionarMedicoViewModel dados)
    {
        var validacao = _adicionarMedicoValidator.Validate(dados);

        if (!validacao.IsValid)
        {
            validacao.AddToModelState(ModelState, string.Empty);
            return View(dados);
        }

        var medico = new Medico
        {
            CRM = dados.CRM,
            Name = dados.Name
        };

        _context.Medicos.Add(medico);
        _context.SaveChanges();

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Editar(int id)
    {
        var medico = _context.Medicos.Find(id);
        
        if (medico != null)
        {
            return View(new EditarMedicoViewModel
            {
                Id = medico.Id,
                CRM = medico.CRM,
                Name = medico.Name
            });
        }

        return NotFound();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Editar(int id, EditarMedicoViewModel dados)
    {
        var validacao = _editarMedicoValidator.Validate(dados);

        if (!validacao.IsValid)
        {
            validacao.AddToModelState(ModelState, string.Empty);
            return View(dados);
        }
        
        var medico = _context.Medicos.Find(id);

        if (medico != null)
        {
            medico.CRM = dados.CRM;
            medico.Name = dados.Name;

            _context.Medicos.Update(medico);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        
        return NotFound();
    }
    
    public IActionResult Excluir(int id)
    {
        var medico = _context.Medicos.Find(id);
        
        if (medico != null)
        {
            return View(new ListarMedicoViewModel()
            {
                Id = medico.Id,
                CRM = medico.CRM,
                Name = medico.Name
            });
        }

        return NotFound();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Excluir(int id, EditarMedicoViewModel dados)
    {
        
        var medico = _context.Medicos.Find(id);

        if (medico != null)
        {
            _context.Medicos.Remove(medico);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        
        return NotFound();
    }
}

SistemaConsultaMedica/Views/Medicos/Adicionar.cshtml
@model SistemaConsultaMedica.ViewModels.Medicos.AdicionarMedicoViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cadastrar Médicos</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Adicionar">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="control-label" asp-for="CRM"></label>
                            <input asp-for="CRM" class="form-control">
                            <span asp-validation-for="CRM" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" asp-for="Name"></label>
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-sm btn-primary" type="submit">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

SistemaConsultaMedica/Views/Medicos/Editar.cshtml
@model SistemaConsultaMedica.ViewModels.Medicos.EditarMedicoViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Editar Médicos</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Editar">
                <div class="card">
                    <div class="card-body">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="form-group">
                            <label class="control-label">CRM</label>
                            <input asp-for="CRM" class="form-control">
                            <span asp-validation-for="CRM" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Nome</label>
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-sm btn-primary" type="submit">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

SistemaConsultaMedica/Views/Medicos/Excluir.cshtml
@model SistemaConsultaMedica.ViewModels.Medicos.ListarMedicoViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Excluir Médicos</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="alert alert-danger">
        <span class="fas fa-warning"></span>
        Deseja realmente excluir este cadastro?
    </div>
    <div class="row">
        <div class="col-12">
            <form asp-action="Excluir">
                <div class="card card-outline card-danger">
                    <div class="card-body">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="form-group">
                            <label class="control-label">CRM</label>
                            <input asp-for="CRM" class="form-control" readonly>
                            <span asp-validation-for="CRM" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Nome</label>
                            <input asp-for="Name" class="form-control" readonly>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col text-right">
                                <button class="btn btn-sm btn-danger" type="submit">Excluir</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

SistemaConsultaMedica/Views/Medicos/Index.cshtml
@model IEnumerable<SistemaConsultaMedica.ViewModels.Medicos.ListarMedicoViewModel>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Médicos</h1>
            </div>
        </div>
    </div>
</section>

<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <form asp-action="Index">
                            <div class="input-group input-group-sm" style="width: 300px;">
                                <input type="text" class="form-control" placeholder="Buscar médico" name="filtro" value="@ViewBag.Filtro">
                                
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <a href="/medicos/adicionar" class="btn btn-outline-primary btn-sm">Novo médico</a>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-head-fixed text-nowrap table-hover">
                        <thead>
                        <tr>
                            <th style="width: 200px">CRM</th>
                            <th>Nome</th>
                            <th style="width: 40px"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var medico in Model)
                        {
                            <tr>
                                <td>
                                    @medico.CRM
                                </td>
                                <td>
                                    @medico.Name
                                </td>
                                <td>
                                    <a href="/medicos/editar/@medico.Id" class="btn btn-sm btn-secondary mr-1" title="Editar médico">
                                        <span class="fas fa-edit"></span>
                                    </a>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                   @if (ViewBag.TotalPaginas > 0)
                   {
                       <ul class="pagination pagination-sm m-0 float-right">
                           @if (ViewBag.NumeroPagina > 1)
                           {
                               <li class="page-item">
                                   <a class="page-link" href="@Url.Action("Index", "Medicos", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina - 1 })">
                                       &laquo; 
                                   </a>
                               </li>
                           }
                           <li class="page-item page-link">Página @ViewBag.NumeroPagina de @ViewBag.TotalPaginas</li>
                           @if (ViewBag.NumeroPagina < @ViewBag.TotalPaginas)
                           {
                               <li class="page-item">
                                   <a class="page-link" href="@Url.Action("Index", "Medicos", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina + 1 })">
                                       &raquo;
                                   </a>
                               </li>
                           }
                       </ul>
                   }
                </div>
            </div>
        </div>
    </div>
</div>